name: Smoke test "latex" build

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
      - src/latex/**
      - .github/workflows/smoke-latex.yaml
      - .github/actions/**
      - build/**
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Smoke test
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        image: latex
